DROP TABLE IF EXISTS Users;
CREATE TABLE Users(
	UserID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(25) NOT NULL,
	email VARCHAR(35) NOT NULL,
	imgaddr VARCHAR(255),
	password VARCHAR(50) NOT NULL,
	UNIQUE(email)

);